apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
spec:
  tls:
    - hosts:
        - backend.example.iteam.se # TODO: CHANGE ME!
      secretName: express-mongo-ts-prod-tls # TODO: CHANGE ME!
  rules:
    - host: backend.example.iteam.se # TODO: CHANGE ME!
      http:
        paths:
          - path: /socket.io/.*
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 4000
