name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 19.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run tests
        run: |
          npm ci
          npm test
        env:
          CI: true

  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        context: [react, react-ts]

    steps:
      - uses: actions/checkout@v3

      - name: Docker build react
        uses: docker/build-push-action@v3
        with:
          context: templates/${{ matrix.context }}
          push: false
